# Generated by Django 5.2.8 on 2025-11-29 17:51

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(default=payments.models.generate_txn_id, max_length=40, unique=True)),
                ('merchant', models.CharField(default='Mohammad Abrar Alam', max_length=120)),
                ('upi_id', models.CharField(default='8757128380@ptaxis', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=payments.models.qr_upload_path)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to=payments.models.invoice_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
